using LayerGenForDotNet4.Models;
using System.Text;

namespace LayerGenForDotNet4.Generator
{
    /// <summary>
    /// Generates C# Data Layer and Business Layer code from a TableInfo.
    /// Improvements over original LayerGen MMX:
    ///  - Full nullable support for ALL value types (int?, bool?, decimal?, etc.)
    ///  - nvarchar(MAX) support (Length == -1)
    ///  - Stored procedures use inline SQL via SqlCommand (no sp_* dependency at code-gen time)
    ///  - No ASP.NET page generation
    ///  - No "Create Custom Procedures" button
    /// </summary>
    public static class CodeGeneratorCS
    {
        // ─── helpers ───────────────────────────────────────────────────────────────

        private static readonly HashSet<string> _csKeywords = new(StringComparer.OrdinalIgnoreCase)
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked",
            "class","const","continue","decimal","default","delegate","do","double","else",
            "enum","event","explicit","extern","false","finally","fixed","float","for",
            "foreach","goto","if","implicit","in","int","interface","internal","is","lock",
            "long","namespace","new","null","object","operator","out","override","params",
            "private","protected","public","readonly","ref","return","sbyte","sealed",
            "short","sizeof","stackalloc","static","string","struct","switch","this","throw",
            "true","try","typeof","uint","ulong","unchecked","unsafe","ushort","using",
            "virtual","void","volatile","while","partial","where","yield","orderby","value",
            "select","join","group","into","from","let","ascending","descending","on","equals"
        };

        private static string SafeName(string name)
        {
            name = name.Replace(".", "");
            return _csKeywords.Contains(name) ? "@" + name : name;
        }

        private static void W(StringBuilder sb, int indent, string line = "")
        {
            sb.AppendLine(string.IsNullOrEmpty(line)
                ? ""
                : new string(' ', indent * 4) + line);
        }

        // Returns full namespace: "DataLayer" | "xxxx.DataLayer" | "BusinessLayer" | "xxxx.BusinessLayer"
        private static string NsLayer(string namespaceName, string layer) =>
            string.IsNullOrWhiteSpace(namespaceName) ? layer : $"{namespaceName}.{layer}";

        private static string SpParamSize(FieldInfo f)
        {
            string t = f.SqlTypeName.ToLowerInvariant();
            if (t is "nvarchar" or "varchar" or "char" or "nchar")
                return f.Length == -1 ? "" : $"({f.Length})";   // MAX = no length param, set -1 at runtime
            if (t is "decimal" or "numeric")
                return $"({f.Precision},{f.Scale})";
            return "";
        }

        // ═══════════════════════════════════════════════════════════════════════════
        //  DATA LAYER
        // ═══════════════════════════════════════════════════════════════════════════

        public static string GenerateDataLayer(TableInfo table, string namespaceName, bool suppressComments,
                                               bool falseErase = false, string falseEraseField = "IsDeleted")
        {
            var sb = new StringBuilder();
            string cn = SafeName(table.TableName);
            string ns = string.IsNullOrEmpty(namespaceName) ? "" : namespaceName + ".";
            string bl = ns + "BusinessLayer.";

            // ── header ────────────────────────────────────────────────────────────
            W(sb, 0, "// ===========================================================================");
            W(sb, 0, "// This file was generated by LayerGenForDotNet4 application");
            W(sb, 0, $"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            W(sb, 0, "// Naser Almadi");
            W(sb, 0, "// nasmn77@gmail.com");
            W(sb, 0, "// ===========================================================================");
            W(sb, 0);
            W(sb, 0, "using System;");
            W(sb, 0, "using System.Data;");
            W(sb, 0, "using Microsoft.Data.SqlClient;");
            W(sb, 0);
            W(sb, 0, $"namespace {NsLayer(namespaceName, "DataLayer")}");
            W(sb, 0, "{");

            W(sb, 1, "[Serializable]");
            W(sb, 1, $"public partial class {cn}");
            W(sb, 1, "{");

            // ── instance variables ────────────────────────────────────────────────
            W(sb, 2, "#region Instance Variables");

            foreach (var f in table.Fields)
                W(sb, 2, $"protected {f.CSharpType()} _{SafeName(f.FieldName)};");

            W(sb, 2, "protected bool _isDirty;");
            W(sb, 2, "protected string _connectString = \"\";");
            W(sb, 2, "protected bool _isUpdate;");
            W(sb, 0);

            // FK backing fields
            foreach (var fk in table.ForeignKeys)
                W(sb, 2, $"protected {bl}{SafeName(fk.PkTable)}? _fk_{fk.FkColumn};");

            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── constructors ──────────────────────────────────────────────────────
            W(sb, 2, "#region Constructors");

            W(sb, 2, $"public {cn}()");
            W(sb, 2, "{");
            W(sb, 3, "SetConnectString();");
            W(sb, 3, "_isUpdate = false;");
            W(sb, 2, "}");
            W(sb, 0);

            if (table.PrimaryKey != null)
            {
                var pkField = table.Fields.First(f => f.FieldName == table.PrimaryKey);
                string pkType = pkField.CSharpType(false);  // primary key always required
                W(sb, 2, $"public {cn}({pkType} primaryKey)");
                W(sb, 2, "{");
                W(sb, 3, "_isUpdate = true;");
                W(sb, 3, "SetConnectString();");
                W(sb, 3, "Get(primaryKey);");
                W(sb, 2, "}");
                W(sb, 0);
            }

            W(sb, 2, $"public {cn}(DataRow row)");
            W(sb, 2, "{");
            W(sb, 3, "_isUpdate = true;");
            W(sb, 3, "SetConnectString();");
            W(sb, 3, "Fill(row);");
            W(sb, 2, "}");
            W(sb, 0);

            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── properties ────────────────────────────────────────────────────────
            W(sb, 2, "#region Properties");

            foreach (var f in table.Fields)
            {
                string propName = SafeName(f.FieldName);
                string ctype = f.CSharpType();
                string varName = $"_{SafeName(f.FieldName)}";

                if (!suppressComments)
                    W(sb, 2, $"/// <summary>{f.FieldName} – {f.SqlTypeName}{(f.IsNullable ? " (nullable)" : "")}</summary>");

                if (f.IsComputed)
                {
                    W(sb, 2, $"public {ctype} {propName} => {varName};");
                }
                else
                {
                    W(sb, 2, $"public {ctype} {propName}");
                    W(sb, 2, "{");
                    W(sb, 3, $"get => {varName};");
                    W(sb, 3, "set");
                    W(sb, 3, "{");
                    W(sb, 4, "_isDirty = true;");
                    W(sb, 4, $"{varName} = value;");
                    W(sb, 3, "}");
                    W(sb, 2, "}");
                }
                W(sb, 0);
            }

            // FK lazy-load properties
            foreach (var fk in table.ForeignKeys)
            {
                string fkType = $"{bl}{SafeName(fk.PkTable)}";
                var fkColField = table.Fields.FirstOrDefault(f => f.FieldName.Equals(fk.FkColumn, StringComparison.OrdinalIgnoreCase));
                string fkCsType = fkColField != null ? fkColField.CSharpType(false) : "int";
                W(sb, 2, $"public {fkType} F{fk.FkColumn}");
                W(sb, 2, "{");
                W(sb, 3, "get");
                W(sb, 3, "{");
                W(sb, 4, $"if (_fk_{fk.FkColumn} == null)");
                W(sb, 5, $"_fk_{fk.FkColumn} = new {fkType}(_{SafeName(fk.FkColumn)});");
                W(sb, 4, $"return _fk_{fk.FkColumn};");
                W(sb, 3, "}");
                W(sb, 3, "set");
                W(sb, 3, "{");
                W(sb, 4, $"_fk_{fk.FkColumn} = value;");
                W(sb, 3, "}");
                W(sb, 2, "}");
                W(sb, 0);
            }

            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── connection routines ───────────────────────────────────────────────
            W(sb, 2, "#region Connection Routines");

            W(sb, 2, "protected void SetConnectString()");
            W(sb, 2, "{");
            W(sb, 3, "_connectString = Universal.GetConnectionString();");
            W(sb, 2, "}");
            W(sb, 0);

            W(sb, 2, "protected string GetConnectString() => _connectString;");
            W(sb, 0);

            W(sb, 2, "protected static string GetConnectionString() => Universal.GetConnectionString();");
            W(sb, 0);

            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── Fill ─────────────────────────────────────────────────────────────
            W(sb, 2, "#region Fill");

            if (!suppressComments) W(sb, 2, "/// <summary>Fills instance variables from a DataRow.</summary>");
            W(sb, 2, "protected void Fill(DataRow row)");
            W(sb, 2, "{");
            foreach (var f in table.Fields)
            {
                string varName = $"_{SafeName(f.FieldName)}";
                string ctype = f.CSharpType();
                W(sb, 3, "try");
                W(sb, 3, "{");

                // All types: check for DBNull
                W(sb, 4, $"if (row[\"{f.FieldName}\"] != DBNull.Value)");
                W(sb, 4, "{");

                if (f.NetType == SqlNetType.ByteArray)
                    W(sb, 5, $"{varName} = (byte[])row[\"{f.FieldName}\"];");
                else if (f.NetType == SqlNetType.String)
                    W(sb, 5, $"{varName} = row[\"{f.FieldName}\"].ToString();");
                else
                {
                    // For nullable value types, cast to the non-nullable base
                    string baseType = ctype.TrimEnd('?');
                    W(sb, 5, $"{varName} = ({baseType})row[\"{f.FieldName}\"];");
                }

                if (f.IsPrimaryKey)
                    W(sb, 5, "_isUpdate = true;");

                W(sb, 4, "}");
                W(sb, 4, "else");
                W(sb, 4, "{");
                W(sb, 5, $"{varName} = {DefaultValueForFill(f)};");
                if (f.IsPrimaryKey)
                    W(sb, 5, "_isUpdate = false;");
                W(sb, 4, "}");

                W(sb, 3, "}");
                W(sb, 3, "catch { }");
                W(sb, 0);
            }
            W(sb, 2, "}");
            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── Copy ─────────────────────────────────────────────────────────────
            W(sb, 2, "#region Copy");

            if (!suppressComments) W(sb, 2, "/// <summary>Copies values from a DataRow (no null check).</summary>");
            W(sb, 2, "public void Copy(DataRow row)");
            W(sb, 2, "{");
            foreach (var f in table.Fields)
            {
                string varName = $"_{SafeName(f.FieldName)}";
                W(sb, 3, "try");
                W(sb, 3, "{");
                if (f.NetType == SqlNetType.ByteArray)
                    W(sb, 4, $"{varName} = (byte[])row[\"{f.FieldName}\"];");
                else if (f.NetType == SqlNetType.String)
                    W(sb, 4, $"{varName} = row[\"{f.FieldName}\"]?.ToString();");
                else
                {
                    string ctype = f.CSharpType();
                    string baseType = ctype.TrimEnd('?');
                    W(sb, 4, $"{varName} = row[\"{f.FieldName}\"] == DBNull.Value ? ({ctype}){DefaultValueForFill(f)} : ({baseType})row[\"{f.FieldName}\"];");
                }
                W(sb, 3, "}");
                W(sb, 3, "catch { }");
                W(sb, 0);
            }
            W(sb, 2, "}");
            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── Get (single record) ───────────────────────────────────────────────
            if (table.PrimaryKey != null)
            {
                var pkField = table.Fields.First(f => f.FieldName == table.PrimaryKey);
                string pkCsType = pkField.CSharpType(false);
                string spSelect = $"[dbo].[{SpName(table.TableName, "Select")}]";

                W(sb, 2, "#region Get");

                if (!suppressComments) W(sb, 2, "/// <summary>Retrieves a single record by primary key.</summary>");
                W(sb, 2, $"private void Get({pkCsType} primaryKey)");
                W(sb, 2, "{");
                W(sb, 3, $"const string sp = \"{spSelect}\";");
                W(sb, 3, "using var conn = new SqlConnection(GetConnectString());");
                W(sb, 3, "using var cmd = new SqlCommand(sp, conn);");
                W(sb, 3, "cmd.CommandType = CommandType.StoredProcedure;");
                W(sb, 3, $"cmd.Parameters.Add(\"@{pkField.FieldName}\", SqlDbType.{pkField.SqlDbTypeStr()}).Value = primaryKey;");
                W(sb, 3, "conn.Open();");
                W(sb, 3, "using var da = new SqlDataAdapter(cmd);");
                W(sb, 3, "var ds = new DataSet();");
                W(sb, 3, "da.Fill(ds);");
                W(sb, 3, "if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)");
                W(sb, 4, "Fill(ds.Tables[0].Rows[0]);");
                W(sb, 2, "}");
                W(sb, 2, "#endregion");
                W(sb, 0);
            }

            // ── GetAll ────────────────────────────────────────────────────────────
            W(sb, 2, "#region GetAll");

            if (!suppressComments) W(sb, 2, "/// <summary>Returns all rows from the table.</summary>");
            W(sb, 2, "public static DataTable? GetAll()");
            W(sb, 2, "{");
            W(sb, 3, $"const string sp = \"[dbo].[{SpName(table.TableName, "GetAll")}]\";");
            W(sb, 3, "using var conn = new SqlConnection(GetConnectionString());");
            W(sb, 3, "using var cmd = new SqlCommand(sp, conn) { CommandType = CommandType.StoredProcedure };");
            W(sb, 3, "conn.Open();");
            W(sb, 3, "using var da = new SqlDataAdapter(cmd);");
            W(sb, 3, "var ds = new DataSet();");
            W(sb, 3, "da.Fill(ds);");
            W(sb, 3, "return ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 ? ds.Tables[0] : null;");
            W(sb, 2, "}");
            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── GetByFK ───────────────────────────────────────────────────────────
            foreach (var fk in table.ForeignKeys)
            {
                var fkColField = table.Fields.FirstOrDefault(f => f.FieldName.Equals(fk.FkColumn, StringComparison.OrdinalIgnoreCase));
                if (fkColField == null) continue;
                string fkCsType = fkColField.CSharpType(false);
                string spGetByFk = $"[dbo].[{SpName(table.TableName, $"GetBy{fk.FkColumn}")}]";

                W(sb, 2, $"#region GetBy{fk.FkColumn}");
                if (!suppressComments) W(sb, 2, $"/// <summary>Returns all rows where {fk.FkColumn} matches.</summary>");
                W(sb, 2, $"public static DataTable? GetBy{fk.FkColumn}({fkCsType} {SafeName(fk.FkColumn)})");
                W(sb, 2, "{");
                W(sb, 3, $"const string sp = \"{spGetByFk}\";");
                W(sb, 3, "using var conn = new SqlConnection(GetConnectionString());");
                W(sb, 3, "using var cmd = new SqlCommand(sp, conn) { CommandType = CommandType.StoredProcedure };");
                W(sb, 3, $"cmd.Parameters.Add(\"@{fk.FkColumn}\", SqlDbType.{fkColField.SqlDbTypeStr()}).Value = {SafeName(fk.FkColumn)};");
                W(sb, 3, "conn.Open();");
                W(sb, 3, "using var da = new SqlDataAdapter(cmd);");
                W(sb, 3, "var ds = new DataSet();");
                W(sb, 3, "da.Fill(ds);");
                W(sb, 3, "return ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 ? ds.Tables[0] : null;");
                W(sb, 2, "}");
                W(sb, 2, "#endregion");
                W(sb, 0);
            }

            // ── Save (Insert / Update) ────────────────────────────────────────────
            if (!table.IsView)
            {
                W(sb, 2, "#region Save");

                // FalseErase field excluded always (managed only by Delete SP)
                bool hasFEField = !string.IsNullOrEmpty(falseEraseField) &&
                    table.Fields.Any(f => f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase));

                // Required fields: NOT NULL, not PK, not computed, not FalseErase
                var requiredFields = table.Fields
                    .Where(f => !f.IsNullable && !f.IsPrimaryKey && !f.IsComputed &&
                                !(hasFEField && f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase)))
                    .ToList();

                if (!suppressComments) W(sb, 2, "/// <summary>Inserts or updates the current record.</summary>");
                W(sb, 2, "public void Save()");
                W(sb, 2, "{");

                // FK cascade saves
                foreach (var fk in table.ForeignKeys)
                {
                    W(sb, 3, $"if (_fk_{fk.FkColumn} != null)");
                    W(sb, 4, $"_fk_{fk.FkColumn}.Save();");
                    W(sb, 0);
                }

                // Build guard condition: _isDirty && required string fields not null
                var guardParts = new List<string> { "!_isDirty" };
                foreach (var rf in requiredFields)
                {
                    bool rfIsRef = rf.NetType is SqlNetType.String or SqlNetType.ByteArray;
                    if (rfIsRef)
                        guardParts.Add($"_{SafeName(rf.FieldName)} == null");
                }
                if (guardParts.Count == 1)
                    W(sb, 3, "if (!_isDirty) return;");
                else
                    W(sb, 3, $"if ({string.Join(" || ", guardParts)}) return;");

                W(sb, 0);

                bool hasPk = table.PrimaryKey != null;
                var pkField2 = hasPk ? table.Fields.First(f => f.FieldName == table.PrimaryKey) : null;

                W(sb, 3, "using var conn = new SqlConnection(GetConnectString());");
                W(sb, 3, "using var cmd = new SqlCommand();");
                W(sb, 3, "cmd.Connection = conn;");
                W(sb, 3, "cmd.CommandType = CommandType.StoredProcedure;");
                W(sb, 0);

                // Add parameters – exclude FalseErase field and identity PK
                foreach (var f in table.Fields)
                {
                    if (f.IsComputed) continue;
                    if (f.IsPrimaryKey && table.IsPrimaryKeyIdentity) continue;
                    if (hasFEField && f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase)) continue;

                    string varName = $"_{SafeName(f.FieldName)}";
                    string sqlDbType = f.SqlDbTypeStr();
                    string ftLow = f.SqlTypeName.ToLowerInvariant();
                    string paramVal = CsParamValue(f, varName);

                    if (ftLow is "decimal" or "numeric")
                        W(sb, 3, $"{{ var _p = cmd.Parameters.Add(\"@{f.FieldName}\", SqlDbType.{sqlDbType}); _p.Precision = {f.Precision}; _p.Scale = {f.Scale}; _p.Value = {paramVal}; }}");
                    else if (ftLow is "nvarchar" or "varchar" or "char" or "nchar")
                    {
                        int sz = f.Length == -1 ? -1 : f.Length;
                        W(sb, 3, $"cmd.Parameters.Add(\"@{f.FieldName}\", SqlDbType.{sqlDbType}, {sz}).Value = {paramVal};");
                    }
                    else
                        W(sb, 3, $"cmd.Parameters.Add(\"@{f.FieldName}\", SqlDbType.{sqlDbType}).Value = {paramVal};");
                }

                // PK parameter
                if (hasPk && pkField2 != null)
                {
                    if (table.IsPrimaryKeyIdentity)
                        W(sb, 3, $"cmd.Parameters.Add(\"@{pkField2.FieldName}\", SqlDbType.{pkField2.SqlDbTypeStr()}).Direction = ParameterDirection.Output;");
                    else
                        W(sb, 3, $"cmd.Parameters.Add(\"@{pkField2.FieldName}\", SqlDbType.{pkField2.SqlDbTypeStr()}).Value = _{SafeName(pkField2.FieldName)};");
                }

                W(sb, 0);
                string spInsert = SpName(table.TableName, "Insert");
                string spUpdate = SpName(table.TableName, "Update");
                W(sb, 3, "if (_isUpdate)");
                W(sb, 3, "{");
                W(sb, 4, $"cmd.CommandText = \"[dbo].[{spUpdate}]\";");
                if (hasPk && pkField2 != null && !table.IsPrimaryKeyIdentity)
                    W(sb, 4, $"cmd.Parameters[\"@{pkField2.FieldName}\"].Direction = ParameterDirection.Input;");
                W(sb, 3, "}");
                W(sb, 3, "else");
                W(sb, 3, "{");
                W(sb, 4, $"cmd.CommandText = \"[dbo].[{spInsert}]\";");
                if (hasPk && pkField2 != null && table.IsPrimaryKeyIdentity)
                    W(sb, 4, $"cmd.Parameters[\"@{pkField2.FieldName}\"].Direction = ParameterDirection.Output;");
                else if (hasPk && pkField2 != null)
                    W(sb, 4, $"cmd.Parameters[\"@{pkField2.FieldName}\"].Direction = ParameterDirection.Input;");
                W(sb, 3, "}");

                W(sb, 0);
                W(sb, 3, "conn.Open();");
                W(sb, 3, "cmd.ExecuteNonQuery();");

                if (hasPk && pkField2 != null && table.IsPrimaryKeyIdentity)
                {
                    string pkVar = $"_{SafeName(pkField2.FieldName)}";
                    string baseCType = pkField2.CSharpType(false).TrimEnd('?');
                    W(sb, 0);
                    W(sb, 3, "if (!_isUpdate)");
                    W(sb, 4, $"{pkVar} = ({baseCType})cmd.Parameters[\"@{pkField2.FieldName}\"].Value;");
                }

                W(sb, 3, "_isDirty = false;");
                W(sb, 3, "_isUpdate = true;");
                W(sb, 2, "}");
                W(sb, 2, "#endregion");
                W(sb, 0);

                // ── Delete ────────────────────────────────────────────────────────
                if (table.PrimaryKey != null)
                {
                    var pkField = table.Fields.First(f => f.FieldName == table.PrimaryKey);
                    string pkVar = $"_{SafeName(pkField.FieldName)}";
                    string spDelete = SpName(table.TableName, "Delete");

                    W(sb, 2, "#region Delete");

                    if (!suppressComments && falseErase && hasFEField)
                    {
                        W(sb, 2, "/// <summary>");
                        W(sb, 2, $"/// The stored procedure [{spDelete}] sets [{falseEraseField}] = 1 (soft delete).");
                        W(sb, 2, "/// Records where " + falseEraseField + " is true are excluded from all queries.");
                        W(sb, 2, "/// </summary>");
                    }
                    else if (!suppressComments)
                        W(sb, 2, "/// <summary>Deletes the current record.</summary>");

                    W(sb, 2, "public void Delete()");
                    W(sb, 2, "{");
                    W(sb, 3, $"const string sp = \"[dbo].[{spDelete}]\";");
                    W(sb, 3, "using var conn = new SqlConnection(GetConnectString());");
                    W(sb, 3, "using var cmd = new SqlCommand(sp, conn);");
                    W(sb, 3, "cmd.CommandType = CommandType.StoredProcedure;");
                    W(sb, 3, $"cmd.Parameters.Add(\"@{pkField.FieldName}\", SqlDbType.{pkField.SqlDbTypeStr()}).Value = {pkVar};");
                    W(sb, 3, "conn.Open();");
                    W(sb, 3, "cmd.ExecuteNonQuery();");
                    W(sb, 2, "}");

                    W(sb, 2, "#endregion");
                    W(sb, 0);
                }
            }

            // ── GetBySQLStatement ─────────────────────────────────────────────────
            W(sb, 2, "#region GetBySQLStatement");

            if (!suppressComments) W(sb, 2, "/// <summary>Execute a raw SQL query and return a DataTable.</summary>");
            W(sb, 2, "public static DataTable? GetBySQLStatement(string sql)");
            W(sb, 2, "{");
            W(sb, 3, "using var conn = new SqlConnection(GetConnectionString());");
            W(sb, 3, "using var cmd = new SqlCommand(sql, conn) { CommandType = CommandType.Text };");
            W(sb, 3, "conn.Open();");
            W(sb, 3, "using var da = new SqlDataAdapter(cmd);");
            W(sb, 3, "var ds = new DataSet();");
            W(sb, 3, "da.Fill(ds);");
            W(sb, 3, "return ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 ? ds.Tables[0] : null;");
            W(sb, 2, "}");
            W(sb, 2, "#endregion");
            W(sb, 0);

            W(sb, 1, "}"); // end class
            W(sb, 0, "}"); // end namespace

            return sb.ToString();
        }

        // ═══════════════════════════════════════════════════════════════════════════
        //  BUSINESS LAYER
        // ═══════════════════════════════════════════════════════════════════════════

        public static string GenerateBusinessLayer(TableInfo table, string namespaceName, bool suppressComments)
        {
            var sb = new StringBuilder();
            string cn = SafeName(table.TableName);

            W(sb, 0, "// ===========================================================================");
            W(sb, 0, "// This file was generated by LayerGenForDotNet4 application");
            W(sb, 0, $"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            W(sb, 0, "// Naser Almadi");
            W(sb, 0, "// nasmn77@gmail.com");
            W(sb, 0, "// ===========================================================================");
            W(sb, 0);
            W(sb, 0, "using System;");
            W(sb, 0, "using System.Data;");
            W(sb, 0);
            W(sb, 0, $"namespace {NsLayer(namespaceName, "BusinessLayer")}");
            W(sb, 0, "{");

            W(sb, 1, "[Serializable]");
            W(sb, 1, $"public class {cn} : {NsLayer(namespaceName, "DataLayer")}.{cn}");
            W(sb, 1, "{");

            // ── Constructors ──────────────────────────────────────────────────────
            W(sb, 2, "#region Constructors");

            W(sb, 2, $"public {cn}() : base() {{ }}");
            W(sb, 0);

            if (table.PrimaryKey != null && !table.IsView)
            {
                var pkField = table.Fields.First(f => f.FieldName == table.PrimaryKey);
                string pkType = pkField.CSharpType(false);
                W(sb, 2, $"public {cn}({pkType} primaryKey) : base(primaryKey) {{ }}");
                W(sb, 0);
            }

            W(sb, 2, $"public {cn}(DataRow row) : base(row) {{ }}");
            W(sb, 0);

            W(sb, 2, "#endregion");
            W(sb, 0);

            // ── Validate / Rollback (placeholder) ─────────────────────────────────
            W(sb, 2, "#region Business Logic");

            if (!suppressComments) W(sb, 2, "/// <summary>Override to add custom validation.</summary>");
            W(sb, 2, "public virtual void Validate()");
            W(sb, 2, "{");
            W(sb, 3, "// TODO: Add validation logic here");
            W(sb, 2, "}");
            W(sb, 0);

            if (!suppressComments) W(sb, 2, "/// <summary>Rollback any unsaved changes.</summary>");
            W(sb, 2, "public virtual void Rollback()");
            W(sb, 2, "{");
            W(sb, 3, "_isDirty = false;");
            W(sb, 2, "}");
            W(sb, 0);

            W(sb, 2, "#endregion");
            W(sb, 0);

            W(sb, 1, "}"); // end class

            // ── Collection class ──────────────────────────────────────────────────
            W(sb, 0);
            W(sb, 1, "[Serializable]");
            W(sb, 1, $"public class {cn}s : System.Collections.Generic.List<{cn}>");
            W(sb, 1, "{");

            if (!suppressComments) W(sb, 2, "/// <summary>Loads all rows from the database into this collection.</summary>");
            W(sb, 2, "public static new System.Collections.Generic.List<BusinessLayer.{cn}> GetAll()");
            W(sb, 2, "{");

            // Fix the class name reference in GetAll
            sb.Replace(
                $"public static new System.Collections.Generic.List<BusinessLayer.{cn}> GetAll()",
                $"public static System.Collections.Generic.List<{cn}> GetAll()"
            );

            W(sb, 3, $"var dt = DataLayer.{cn}.GetAll();");
            W(sb, 3, $"var list = new System.Collections.Generic.List<{cn}>();");
            W(sb, 3, "if (dt == null) return list;");
            W(sb, 3, "foreach (DataRow row in dt.Rows)");
            W(sb, 4, $"list.Add(new {cn}(row));");
            W(sb, 3, "return list;");
            W(sb, 2, "}");
            W(sb, 0);

            W(sb, 1, "}");

            W(sb, 0, "}"); // end namespace

            return sb.ToString();
        }

        // ═══════════════════════════════════════════════════════════════════════════
        //  STORED PROCEDURES SQL SCRIPT
        // ═══════════════════════════════════════════════════════════════════════════

        public static string GenerateStoredProcedures(TableInfo table, bool suppressComments, bool falseErase, string falseEraseField, string schema = "dbo")
        {
            var sb = new StringBuilder();
            string tbl = table.TableName;
            string pk = table.PrimaryKey ?? "";
            var pkField = pk != "" ? table.Fields.FirstOrDefault(f => f.FieldName == pk) : null;

            void Line(string s = "") => sb.AppendLine(s);
            string sch = $"[{(string.IsNullOrWhiteSpace(schema) ? "dbo" : schema)}]";
            string genDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            void SpHeader()
            {
                Line("-- ===========================================================================");
                Line("-- This file was generated by LayerGenForDotNet4 application");
                Line($"-- Generated on: {genDate}");
                Line("-- Naser Almadi");
                Line("-- nasmn77@gmail.com");
                Line("-- ===========================================================================");
            }
            void DropCreate(string procName)
            {
                Line($"IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = '{procName}')");
                Line($"    DROP PROCEDURE {sch}.[{procName}]");
                Line("GO");
                Line();
            }
            void GoGrant(string procName)
            {
                Line("GO");
                Line("-- ======= Permissions =======");
                Line($"GRANT EXECUTE ON {sch}.[{procName}] TO [public]");
                Line("GO");
                Line();
            }

            // ── SELECT ────────────────────────────────────────────────────────────
            if (pk != "" && pkField != null)
            {
                string procSelect = SpName(tbl, "Select");
                DropCreate(procSelect);
                if (!suppressComments) Line($"-- SELECT one record from {tbl} by primary key");
                SpHeader();
                Line($"CREATE PROCEDURE {sch}.[{procSelect}]");
                Line($"    @{pk} {GetSqlTypeDecl(pkField)} = NULL");
                Line("AS");
                Line("SET NOCOUNT ON;");
                Line($"SELECT {BuildSelectColumns(table.Fields)}");
                Line($"FROM {sch}.[{tbl}]");
                Line($"WHERE [{pk}] = @{pk}");
                GoGrant(procSelect);
            }

            // ── INSERT ────────────────────────────────────────────────────────────
            if (!table.IsView)
            {
                string procInsert = SpName(tbl, "Insert");
                DropCreate(procInsert);
                if (!suppressComments) Line($"-- INSERT a new record into {tbl}");
                SpHeader();
                Line($"CREATE PROCEDURE {sch}.[{procInsert}]");

                // Insert params: exclude FalseErase field (always hardcoded to 0 in INSERT, never a parameter)
                bool hasFEField = falseEraseField != "" && table.Fields.Any(f => f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase));
                var insertParams = table.Fields
                    .Where(f => !f.IsComputed &&
                        !(hasFEField && f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase)))
                    .ToList();

                bool first = true;
                foreach (var f in insertParams)
                {
                    string prefix = first ? "    " : "   ,";
                    first = false;
                    bool isOutputPk = f.IsPrimaryKey && table.IsPrimaryKeyIdentity;
                    string outStr = isOutputPk ? " OUTPUT" : "";
                    string nullDefault = (!isOutputPk && f.IsNullable) ? " = NULL" : "";
                    Line($"{prefix}@{f.FieldName} {GetSqlTypeDecl(f)}{outStr}{nullDefault}");
                }
                Line("AS");
                Line("SET NOCOUNT ON;");
                Line();

                // Columns to insert: exclude identity PK; FalseErase col gets hardcoded value 0
                var nonIdentityCols = table.Fields
                    .Where(f => !f.IsComputed && !(f.IsPrimaryKey && table.IsPrimaryKeyIdentity))
                    .ToList();

                // FalseErase column: NOT a parameter – written inline as literal 0 in VALUES
                var insertCols = nonIdentityCols
                    .Where(f => !(hasFEField && f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase)))
                    .Select(f => $"[{f.FieldName}]");
                var insertVals = nonIdentityCols
                    .Where(f => !(hasFEField && f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase)))
                    .Select(f => $"@{f.FieldName}");

                string feCols = hasFEField ? $", [{falseEraseField}]" : "";
                string feVals = hasFEField ? ", 0" : "";

                Line($"INSERT INTO {sch}.[{tbl}]");
                Line($"    ({string.Join(", ", insertCols)}{feCols})");
                Line("VALUES");
                Line($"    ({string.Join(", ", insertVals)}{feVals})");
                Line();
                if (pk != "" && table.IsPrimaryKeyIdentity)
                    Line($"SET @{pk} = SCOPE_IDENTITY()");
                GoGrant(procInsert);

                // ── UPDATE ────────────────────────────────────────────────────────
                string procUpdate = SpName(tbl, "Update");
                DropCreate(procUpdate);
                if (!suppressComments) Line($"-- UPDATE an existing record in {tbl}");
                SpHeader();
                Line($"CREATE PROCEDURE {sch}.[{procUpdate}]");

                // Exclude FalseErase field from Update – it is managed only by Delete
                first = true;
                foreach (var f in table.Fields.Where(f => !f.IsComputed &&
                    !(hasFEField && f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase))))
                {
                    string prefix = first ? "    " : "   ,";
                    first = false;
                    string nullDefault = (!f.IsPrimaryKey && f.IsNullable) ? " = NULL" : "";
                    Line($"{prefix}@{f.FieldName} {GetSqlTypeDecl(f)}{nullDefault}");
                }
                Line("AS");
                Line("SET NOCOUNT ON;");
                Line();
                Line($"UPDATE {sch}.[{tbl}]");
                Line("SET");
                var updateFields = table.Fields
                    .Where(f => !f.IsComputed && !f.IsPrimaryKey &&
                        !(hasFEField && f.FieldName.Equals(falseEraseField, StringComparison.OrdinalIgnoreCase)))
                    .ToList();
                for (int i = 0; i < updateFields.Count; i++)
                {
                    string sep = i < updateFields.Count - 1 ? "," : "";
                    Line($"    [{updateFields[i].FieldName}] = @{updateFields[i].FieldName}{sep}");
                }
                if (pk != "")
                    Line($"WHERE [{pk}] = @{pk}");
                GoGrant(procUpdate);
            }

            // ── DELETE ────────────────────────────────────────────────────────────
            if (pk != "" && pkField != null && !table.IsView)
            {
                string procDelete = SpName(tbl, "Delete");
                DropCreate(procDelete);
                if (!suppressComments) Line($"-- DELETE a record from {tbl}");
                SpHeader();
                Line($"CREATE PROCEDURE {sch}.[{procDelete}]");
                Line($"    @{pk} {GetSqlTypeDecl(pkField)} = NULL");
                Line("AS");
                Line("SET NOCOUNT ON;");
                if (falseErase && falseEraseField != "")
                {
                    // Soft delete: set the FalseErase field to 1
                    Line($"UPDATE {sch}.[{tbl}] SET [{falseEraseField}] = 1 WHERE [{pk}] = @{pk}");
                }
                else
                {
                    Line($"DELETE FROM {sch}.[{tbl}] WHERE [{pk}] = @{pk}");
                }
                GoGrant(procDelete);
            }

            // ── GET ALL ───────────────────────────────────────────────────────────
            {
                string procGetAll = SpName(tbl, "GetAll");
                DropCreate(procGetAll);
                if (!suppressComments) Line($"-- Get all records from {tbl}");
                SpHeader();
                Line($"CREATE PROCEDURE {sch}.[{procGetAll}]");
                Line("AS");
                Line("SET NOCOUNT ON;");
                Line($"SELECT {BuildSelectColumns(table.Fields)}");
                Line($"FROM {sch}.[{tbl}]");
                if (falseErase && falseEraseField != "")
                    Line($"WHERE [{falseEraseField}] = 0");
                GoGrant(procGetAll);
            }

            // ── GET BY FK ─────────────────────────────────────────────────────────
            foreach (var fk in table.ForeignKeys)
            {
                var fkColField = table.Fields.FirstOrDefault(f => f.FieldName.Equals(fk.FkColumn, StringComparison.OrdinalIgnoreCase));
                if (fkColField == null) continue;

                string procGetByFk = SpName(tbl, $"GetBy{fk.FkColumn}");
                DropCreate(procGetByFk);
                if (!suppressComments) Line($"-- Get all records from {tbl} where {fk.FkColumn} matches");
                SpHeader();
                Line($"CREATE PROCEDURE {sch}.[{procGetByFk}]");
                Line($"    @{fk.FkColumn} {GetSqlTypeDecl(fkColField)} = NULL");
                Line("AS");
                Line("SET NOCOUNT ON;");
                Line($"SELECT {BuildSelectColumns(table.Fields)}");
                Line($"FROM {sch}.[{tbl}]");
                if (falseErase && falseEraseField != "")
                    Line($"WHERE [{falseEraseField}] = 0 AND [{fk.FkColumn}] = @{fk.FkColumn}");
                else
                    Line($"WHERE [{fk.FkColumn}] = @{fk.FkColumn}");
                GoGrant(procGetByFk);
            }

            return sb.ToString();
        }

        // ═══════════════════════════════════════════════════════════════════════════
        //  UNIVERSAL FILE
        // ═══════════════════════════════════════════════════════════════════════════

        public static string GenerateUniversalFile(string namespaceName, string connectionString, bool suppressComments)
        {
            var sb = new StringBuilder();
            W(sb, 0, "// ===========================================================================");
            W(sb, 0, "// This file was generated by LayerGenForDotNet4 application");
            W(sb, 0, $"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            W(sb, 0, "// Naser Almadi");
            W(sb, 0, "// nasmn77@gmail.com");
            W(sb, 0, "// ===========================================================================");
            W(sb, 0);
            W(sb, 0, "using Microsoft.Extensions.Configuration;");
            W(sb, 0);
            W(sb, 0, $"namespace {NsLayer(namespaceName, "DataLayer")}");
            W(sb, 0, "{");
            W(sb, 1, "public static class Universal");
            W(sb, 1, "{");
            if (!suppressComments)
                W(sb, 2, "/// <summary>Return the connection string for the database.</summary>");
            W(sb, 2, "public static string GetConnectionString()");
            W(sb, 2, "{");
            W(sb, 3, "// Option 1: Hard-coded (for testing only – not recommended for production)");
            W(sb, 3, $"// return \"{EscapeString(connectionString)}\";");
            W(sb, 3);
            W(sb, 3, "// Option 2: Read from appsettings.json");
            W(sb, 3, "// var config = new ConfigurationBuilder()");
            W(sb, 3, "//     .AddJsonFile(\"appsettings.json\")");
            W(sb, 3, "//     .Build();");
            W(sb, 3, "// return config.GetConnectionString(\"SqlConnection\") ?? string.Empty;");
            W(sb, 3);
            W(sb, 3, "// Option 3: Read from environment variable");
            W(sb, 3, "// return Environment.GetEnvironmentVariable(\"SQLCONNSTR_SqlConnection\") ?? string.Empty;");
            W(sb, 3);
            W(sb, 3, "// ── ACTIVE ──────────────────────────────────────────────────────────────");
            W(sb, 3, $"return \"{EscapeString(connectionString)}\";");
            W(sb, 2, "}");
            W(sb, 1, "}");
            W(sb, 0, "}");
            return sb.ToString();
        }

        // ─── private helpers ───────────────────────────────────────────────────────

        /// <summary>
        /// ProperCase stored procedure name: sp_Tbl_1Test_Select
        /// Each segment capitalizes the first alphabetic character (after any leading digits).
        /// e.g. table "1test" → segment "1Test", table "tbl_1test" → "sp_Tbl_1Test_Select"
        /// </summary>
        private static string SpName(string tableName, string suffix)
        {
            string[] parts = tableName.Split('_');
            var sb2 = new StringBuilder();
            foreach (var p in parts)
            {
                sb2.Append('_');
                if (p.Length == 0) continue;
                // Find first alpha char and capitalize it; keep leading digits as-is
                bool capitalized = false;
                for (int i = 0; i < p.Length; i++)
                {
                    if (!capitalized && char.IsLetter(p[i]))
                    {
                        sb2.Append(char.ToUpperInvariant(p[i]));
                        capitalized = true;
                    }
                    else
                    {
                        sb2.Append(p[i]);
                    }
                }
            }
            return "sp" + sb2 + "_" + suffix;
        }

        private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string BuildSelectColumns(List<FieldInfo> fields)
        {
            return string.Join(", ", fields.Select(f => $"[{f.FieldName}]"));
        }

        private static string GetSqlTypeDecl(FieldInfo f)
        {
            string t = f.SqlTypeName.ToLowerInvariant();
            return t switch
            {
                "nvarchar" or "varchar" => f.Length == -1 ? $"{t.ToUpper()}(MAX)" : $"{t.ToUpper()}({f.Length})",
                "nchar" or "char" => $"{t.ToUpper()}({f.Length})",
                "decimal" or "numeric" => $"{t.ToUpper()}({f.Precision},{f.Scale})",
                _ => t.ToUpper()
            };
        }

        private static string NullableParamValue(FieldInfo f, string varName)
            => CsParamValue(f, varName);

        /// <summary>
        /// C# parameter value expression:
        /// - Nullable types (string?, bool?, int?…) → (object?)var ?? DBNull.Value
        /// - NOT NULL value types (bool, int…)      → var  (always has a value)
        /// - NOT NULL string                         → (object?)var ?? DBNull.Value (defensive)
        /// </summary>
        private static string CsParamValue(FieldInfo f, string varName)
        {
            bool isRefType = f.NetType is SqlNetType.String or SqlNetType.ByteArray;
            // Nullable OR reference types → guard with DBNull
            if (f.IsNullable || isRefType)
                return $"(object?){varName} ?? DBNull.Value";
            // NOT NULL value type → send directly
            return varName;
        }

        private static string DefaultValueForFill(FieldInfo f)
        {
            if (f.IsNullable) return "null";
            return f.NetType switch
            {
                SqlNetType.String => "null",
                SqlNetType.ByteArray => "null",
                SqlNetType.Bool => "false",
                SqlNetType.Int or SqlNetType.Long or SqlNetType.Short or SqlNetType.Byte => "0",
                SqlNetType.Decimal => "0m",
                SqlNetType.Double => "0.0",
                SqlNetType.Float => "0f",
                SqlNetType.DateTime => "DateTime.MinValue",
                SqlNetType.TimeSpan => "TimeSpan.Zero",
                SqlNetType.Guid => "Guid.Empty",
                _ => "null"
            };
        }

        // ═══════════════════════════════════════════════════════════════════════════
        //  INTERFACES FILE
        // ═══════════════════════════════════════════════════════════════════════════

        public static string GenerateInterfacesFile(string namespaceName, bool suppressComments)
        {
            var sb = new StringBuilder();
            W(sb, 0, "// ===========================================================================");
            W(sb, 0, "// This file was generated by LayerGenForDotNet4 application");
            W(sb, 0, $"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            W(sb, 0, "// Naser Almadi");
            W(sb, 0, "// nasmn77@gmail.com");
            W(sb, 0, "// ===========================================================================");
            W(sb, 0);
            int b = 0;
            if (!string.IsNullOrEmpty(namespaceName))
            {
                W(sb, 0, $"namespace {namespaceName}");
                W(sb, 0, "{");
                b = 1;
            }
            W(sb, b, "public interface IBusiness");
            W(sb, b, "{");
            W(sb, b + 1, "void Validate();");
            W(sb, b + 1, "void Rollback();");
            W(sb, b, "}");
            if (!string.IsNullOrEmpty(namespaceName)) W(sb, 0, "}");
            return sb.ToString();
        }

        // ═══════════════════════════════════════════════════════════════════════════
        //  CUSTOM FILES
        // ═══════════════════════════════════════════════════════════════════════════

        public static string GenerateDataCustomFile(TableInfo table, string namespaceName, bool suppressComments)
        {
            var sb = new StringBuilder();
            string cn = SafeName(table.TableName);
            W(sb, 0, "// ===========================================================================");
            W(sb, 0, "// This file was generated by LayerGenForDotNet4 application");
            W(sb, 0, $"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            W(sb, 0, "// Naser Almadi");
            W(sb, 0, "// nasmn77@gmail.com");
            W(sb, 0, "// ===========================================================================");
            W(sb, 0);
            W(sb, 0, "using System.Data;");
            W(sb, 0, "using Microsoft.Data.SqlClient;");
            W(sb, 0);
            string dlNs = NsLayer(namespaceName, "DataLayer");
            W(sb, 0, $"namespace {dlNs}");
            W(sb, 0, "{");
            int b = 1;
            W(sb, b, $"public partial class {cn}");
            W(sb, b, "{");
            W(sb, b + 1, "#region Custom Data Queries");
            W(sb, b + 1, "// Add your custom data query methods here.");
            W(sb, b + 1, "// Example:");
            W(sb, b + 1, $"// public static DataTable? GetByCustom(int param)");
            W(sb, b + 1, "// {");
            W(sb, b + 1, $"//     const string sp = \"[dbo].[{SpName(table.TableName, "CustomSelect")}]\";");
            W(sb, b + 1, "//     ...");
            W(sb, b + 1, "// }");
            W(sb, b + 1, "#endregion");
            W(sb, b, "}");
            if (!string.IsNullOrEmpty(namespaceName)) W(sb, 0, "}");
            return sb.ToString();
        }

        public static string GenerateBusinessCustomFile(TableInfo table, string namespaceName, bool suppressComments)
        {
            var sb = new StringBuilder();
            string cn = SafeName(table.TableName);
            W(sb, 0, "// ===========================================================================");
            W(sb, 0, "// This file was generated by LayerGenForDotNet4 application");
            W(sb, 0, $"// Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            W(sb, 0, "// Naser Almadi");
            W(sb, 0, "// nasmn77@gmail.com");
            W(sb, 0, "// ===========================================================================");
            W(sb, 0);
            W(sb, 0, "using System.Data;");
            W(sb, 0);
            string blNs = NsLayer(namespaceName, "BusinessLayer");
            W(sb, 0, $"namespace {blNs}");
            W(sb, 0, "{");
            int b = 1;
            W(sb, b, $"public partial class {cn}");
            W(sb, b, "{");
            W(sb, b + 1, "#region Custom Business Logic");
            W(sb, b + 1, "// Add your custom business logic here.");
            W(sb, b + 1, "// Example:");
            W(sb, b + 1, "// public override void Validate()");
            W(sb, b + 1, "// {");
            W(sb, b + 1, "//     base.Validate();");
            W(sb, b + 1, "//     // Custom validation...");
            W(sb, b + 1, "// }");
            W(sb, b + 1, "#endregion");
            W(sb, b, "}");
            if (!string.IsNullOrEmpty(namespaceName)) W(sb, 0, "}");
            return sb.ToString();
        }
    }
}
